server:
  address: 0.0.0.0
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/main_db
    username: postgres
    password: 0000
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

rest:
  specialist-service-url: http://127.0.0.1:8082/api/specialists
  registration-service-url: http://127.0.0.1:8083/api/registrations
